"""NVIDIA Tegra / L4T content-evidence parser.

Content-evidence counterweight to the 24 filename-only Tegra patterns
shipped 2026-05-18 (commit ``3000a9e`` at
``patterns_loader.py`` + ``firmware_patterns.yaml``). The filename
patterns catch the common cases (``bpmp.bin``, ``spe.bin``,
``tegra186-*.dtb``, ``DEVICE_A-*.img``, etc.); this parser catches the
operator-renamed cases where content evidence — ELF section names,
FDT compatibles, Android boot.img cmdline, Debian ar magic — confirms
``vendor=nvidia`` regardless of filename.

Also extracts the L4T BSP release string ("R32.3.1" etc.) from the
``/etc/nv_tegra_release``-style banner when present in the blob's
head window. The release string is surfaced as TOP-LEVEL
``blob.metadata["l4t_release"]`` (NOT nested under the ``tegra_blob``
dict) so that cve_matcher's one-level-deep ``_stringify_metadata``
walker reaches it — this is the activation pre-req for the 6
forward-prepared NVIDIA Tegra CVE pins shipped 2026-05-15 (commit
``6bc1c1d``) per Reviewer B B4 finding from postmortem 2026-05-15.

Per user direction 2026-05-18 ("we won't be the only ones ingesting
files... don't hard-code strict formats"), the parser must be
adaptive: content always wins over filename, and the confidence
ladder (high/medium/low) lets downstream consumers see evidence
quality rather than binary accept/reject.

In-scope formats (this commit)
==============================

1. **ELF** (``\\x7fELF`` at offset 0) — bpmp / spe / adsp / cboot /
   nvtboot / mb1 / mb2 kernel-mode binaries. Disambiguation:
   read first 64 KB looking for Tegra-specific section names
   (``.bpmp_fw`` / ``.spe_fw`` / ``.adsp_fw`` / ``.tegra_cboot``),
   symbol/string prefixes (``T18x_`` / ``T19x_`` / ``T21x_`` /
   ``T23x_`` / ``tegra_`` / ``bpmp_``), or SOC strings in .rodata
   (``nvidia,tegra186`` / ``nvidia,tegra194`` / ``nvidia,tegra210``
   / ``nvidia,tegra234`` / ``NVIDIA Tegra`` / ``NVIDIA Jetson``).
   HIGH confidence on canonical evidence; MEDIUM on only-rodata
   match (operator may have stripped section names but kept the
   build banner).

   Ref: ELF gABI; SOC identifier convention is NVIDIA's own
   per the upstream Linux ``arch/arm64/boot/dts/nvidia/`` tree
   and L4T BSP source.

2. **FDT** (``\\xd0\\x0d\\xfe\\xed`` at offset 0, big-endian) —
   tegra*-*.dtb. Disambiguation: scan first 64 KB for
   ``nvidia,tegra<soc>`` compatible strings + ``Jetson`` / ``Tegra``
   model strings. HIGH confidence on canonical evidence.

   Ref: Devicetree Specification v0.4 §5.2; libfdt FDT_MAGIC.

3. **Android boot.img** (``ANDROID!`` 8-byte ASCII at offset 0) —
   ``DEVICE_A-*.img`` / Jetson Linux ``boot.img``. The magic is NOT
   Tegra-specific (used by stock Android too); confidence is
   MEDIUM only when cmdline / kernel preamble carries a Tegra
   hint (``tegra`` / ``jetson`` / ``nvidia``). Without those
   hints the parser returns None and the filename-stage decision
   carries.

   Ref: AOSP ``system/tools/mkbootimg/include/bootimg/bootimg.h``
   ``#define BOOT_MAGIC "ANDROID!"``.

4. **Debian ar** (``!<arch>\\n`` 8-byte at offset 0) — ``.deb``
   packages. The OUTER container is genuinely Debian; the parser
   returns ``vendor=debian`` so downstream unblob unpacks the
   control archive (the inner components get classified at their
   own filename layer via firmware_patterns.yaml entries like
   ``nvidia-l4t-bootloader_*_arm64.deb``).

   Ref: GNU ar format (``man ar``).

Deferred — see TBDs in the spec
================================

5. **NVIDIA wrapper for tos*.img / mb1*.bin** — NVIDIA signs MB1 /
   TOS images with a wrapper header whose magic bytes are NOT
   pinned from any public source surveyed (NVIDIA L4T docs, OE4T
   meta-tegra GitHub, U-Boot Tegra drivers, developer forums).
   Without authoritative bytes, this parser does NOT guess at the
   magic — filename-pattern stays authoritative. A future session
   with access to a live BSP install (``/opt/nvidia/Linux_for_
   Tegra/``) can ``xxd | head`` a known mb1.bin / tos.img and pin
   the bytes in a follow-up commit.

6. **NVIDIA BUP container (.bup)** — same TBD status as (5).
   Generated by L4T BSP's ``Linux_for_Tegra/bootloader/bup_
   generator/`` scripts; magic not pinned from public sources.
   Filename-pattern carries until magic is verified.

Both deferrals are explicit per Rule #19 (evidence-first — never
guess at magic bytes) and Rule #6 (CLI-flag verification — the
analog for parser magic). When the magic is pinned, a follow-up
commit extends ``parse_tegra_blob`` to dispatch on it.

Integration
===========

``detector.py:detect_hardware_firmware`` invokes
``parse_tegra_blob`` as a CONTENT-EVIDENCE SECOND PASS immediately
after the filename-stage parser, gated on ``magic[:4]`` membership
in the Tegra-eligible set. When the parser returns a non-None
ParsedBlob with vendor=nvidia / chipset_target, the detector
merges those into the existing ParsedBlob (Rule #19 — content
beats filename). Cheap on non-Tegra magic: one head read + a
short byte-scan, no LIEF / fdt cold-import.

Contract
========

* MUST NOT raise. On any internal error return None so detection
  continues for other blobs.
* Returns ``ParsedBlob`` with ``vendor="nvidia"`` whenever
  Tegra-specific evidence fires. For Debian ar, returns
  ``vendor="debian"`` — the outer container's vendor is
  genuinely Debian.
* ``chipset_target`` populated to one of ``"t186"`` / ``"t194"``
  / ``"t210"`` / ``"t234"`` when SOC evidence is identifiable;
  ``None`` otherwise.
* ``metadata["tegra_blob"]`` carries the structured evidence dict
  (subset / confidence / matched tokens / soc_token).

Confidence ladder
=================

* **high** — Canonical evidence:
  - ELF with Tegra section names OR Tegra symbol prefixes
  - FDT with ``nvidia,tegra*`` compatible
  - Debian ar magic (the outer container is canonically Debian)
* **medium** — Partial evidence:
  - ELF with only ``.rodata`` SOC strings (operator-stripped sections)
  - Android boot.img with Tegra cmdline hints
* **None** (returns None) — No Tegra evidence found; filename-pattern
  carries.
"""

from __future__ import annotations

import logging
import re
from typing import Any

from app.services.hardware_firmware.parsers.base import ParsedBlob

logger = logging.getLogger(__name__)


# Magic byte constants.
_ELF_MAGIC = b"\x7fELF"
_FDT_MAGIC = b"\xd0\x0d\xfe\xed"  # big-endian; libfdt FDT_MAGIC 0xd00dfeed
_ANDROID_BOOT_MAGIC = b"ANDROID!"
_DEB_AR_MAGIC = b"!<arch>\n"


# Scan budgets. Tuned for cheapness — the parser runs on every
# eligible-magic blob the detector walks, so per-call cost must be
# bounded. Bigger windows are not needed for the byte-scan checks
# the parser performs (no full ELF / FDT parse on the hot path).
_HEAD_SCAN_BYTES = 64 * 1024  # ELF section headers + .rodata strings + FDT model
_BOOTIMG_CMDLINE_SCAN_BYTES = 16 * 1024  # Android boot.img header + cmdline + kernel preamble


# ELF Tegra-specific evidence — section names that cannot occur in
# generic ARM ELFs.
_TEGRA_ELF_SECTION_TOKENS: tuple[bytes, ...] = (
    b".bpmp_fw",
    b".spe_fw",
    b".adsp_fw",
    b".tegra_cboot",
    b".tegra_",
)

# ELF symbol/string prefixes that anchor to Tegra SOCs. Pairs with
# ARM/AArch64 e_machine gate (an x86_64 ELF with ``tegra_init`` is
# a host-side build tool, not a Tegra firmware blob — but the
# byte-scan can't distinguish e_machine cheaply, so the rodata SOC
# string check below is the safer second-stage filter).
_TEGRA_ELF_SYMBOL_PREFIXES: tuple[bytes, ...] = (
    b"T18x_",  # TX2 / T186
    b"T19x_",  # Xavier / T194
    b"T21x_",  # TX1+Nano / T210
    b"T23x_",  # Orin / T234
)

# .rodata SOC tokens — definitive Tegra evidence regardless of
# section names (operator may have stripped section names but the
# build banner survives in .rodata).
_TEGRA_SOC_TOKENS: tuple[bytes, ...] = (
    b"nvidia,tegra186",
    b"nvidia,tegra194",
    b"nvidia,tegra210",
    b"nvidia,tegra234",
    b"NVIDIA Tegra",
    b"NVIDIA Jetson",
)

# SOC token → chipset_target mapping.
_SOC_TO_CHIPSET: dict[bytes, str] = {
    b"nvidia,tegra186": "t186",
    b"nvidia,tegra194": "t194",
    b"nvidia,tegra210": "t210",
    b"nvidia,tegra234": "t234",
    b"T18x_": "t186",
    b"T19x_": "t194",
    b"T21x_": "t210",
    b"T23x_": "t234",
}

# FDT Tegra model/compatible tokens — Jetson DTBs always carry at
# least one of these in the root node.
_TEGRA_FDT_MODEL_TOKENS: tuple[bytes, ...] = (
    b"nvidia,tegra",  # nvidia,tegra186 / nvidia,tegra194 / etc.
    b"nvidia,p",  # Jetson board IDs: nvidia,p3450 / p3448 / p3509 / p2972
    b"NVIDIA Jetson",
    b"NVIDIA Tegra",
    b"Jetson Nano",
    b"Jetson TX1",
    b"Jetson TX2",
    b"Jetson Xavier",
    b"Jetson Orin",
)

# Android boot.img Tegra-hint tokens — searched in the cmdline +
# kernel-preamble region. Without ANY of these the parser returns
# None for Android boot.img magic (refuses to fabricate Tegra
# attribution from format-only evidence).
_TEGRA_BOOTIMG_TOKENS: tuple[bytes, ...] = (
    b"tegra",
    b"jetson",
    b"nvidia",
    b"androidboot.product=jetson",
    b"androidboot.hardware=tegra",
)


# L4T BSP release banner per NVIDIA's ``/etc/nv_tegra_release`` format:
#   ``# R32 (release), REVISION: 3.1, GCID: <id>, BOARD: <board>, EABI:
#   aarch64, DATE: <ts>``
#
# Captures the major release number (R28 / R31 / R32 / R35 / R36 — the
# JetPack-major series) and the dotted revision (e.g. 3.1) for
# concatenation as ``R<major>.<rev_x>.<rev_y>`` (``R32.3.1``).
#
# Pattern handles the canonical comment-prefixed form AND the bare
# (no leading ``#``) form sometimes embedded in BSP scripts / .rodata.
# Optional whitespace around ``,`` and ``:`` per L4T BSP authoring.
# Re-checked on real R32.3.1 / R32.6.1 / R35.4.1 / R36.4.0 banner
# samples per Rule #19 (evidence-first).
_L4T_RELEASE_BANNER_RE = re.compile(
    rb"#?\s*R(\d{2,3})\s*\(release\)\s*,\s*REVISION:\s*(\d+)\.(\d+)",
    re.IGNORECASE,
)

# L4T BSP tarball / extraction-path naming convention: NVIDIA distributes
# the BSP as ``L4T_BSP_SecureBoot.R32.3.1.tar.gz`` / ``Jetson_Linux_R35.4.1
# _aarch64.tbz2`` etc. The L4T release is encoded in the FILENAME of the
# distribution archive. Per the 2026-05-15 DEVICE_A corpus analysis, standalone
# bootloader / DTB / MCU blobs do NOT carry the banner inline — the
# banner lives only in /etc/nv_tegra_release in the rootfs OR in the
# BSP archive's directory name after unblob/unpack.
#
# This regex captures the path-derived form so that operator-renamed
# bootloader blobs landed under an L4T BSP extraction directory STILL
# pick up the L4T release via path inference. Activation pre-req for
# the 6 forward-prepared NVIDIA Tegra CVE pins on the DEVICE_A-class corpus
# (Jetson firmware shipped as L4T BSP archives, not as rootfs images).
#
# Matches ``R<N>.<x>.<y>`` or ``R<N>.<x>`` patterns anywhere in the
# path. Uses non-alphanumeric lookarounds (NOT ``\b``) because path
# segments are typically underscore-separated (e.g.
# ``Tegra210_Linux_R28.2_aarch64``) — ``_`` IS a word character in
# Python regex, so ``\bR`` between ``_`` and ``R`` fails (both are
# word chars). Negative lookbehind for alphanumeric permits ``_``,
# ``/``, ``-``, ``.`` as preceding separators. Negative lookahead for
# ``.<digit>`` prevents matching ``R28.2`` when ``R28.2.3`` is the
# real string. The triple form is preferred over the pair form via
# the alternation order — first match wins in Python re.search.
_L4T_RELEASE_PATH_RE = re.compile(
    r"(?<![A-Za-z0-9])R(\d{2,3})\.(\d+)\.(\d+)(?!\.?\d)"
    r"|(?<![A-Za-z0-9])R(\d{2,3})\.(\d+)(?!\.?\d)",
    re.IGNORECASE,
)


def _extract_l4t_release(head: bytes) -> str | None:
    """Scan ``head`` for the /etc/nv_tegra_release banner string.

    Returns ``"R<N>.<x>.<y>"`` (e.g. ``"R32.3.1"``) on hit, or ``None``
    if no banner is found. The output format matches the version_regex
    patterns in the 6 forward-prepared NVIDIA Tegra CVE pins
    (``r32\\.3\\.``, ``r3[01]\\b``, etc.) shipped 2026-05-15 in
    ``known_firmware.yaml``.

    Per Reviewer B B4 (postmortem 2026-05-15), the caller MUST store
    this string at TOP-LEVEL ``blob.metadata["l4t_release"]`` — NOT
    inside the nested ``tegra_blob`` dict — so cve_matcher's
    one-level-deep ``_stringify_metadata`` walker reaches it. Storing
    nested would silently defeat the version_regex match path.
    """
    m = _L4T_RELEASE_BANNER_RE.search(head)
    if not m:
        return None
    major = m.group(1).decode("ascii", errors="replace")
    revision_x = m.group(2).decode("ascii", errors="replace")
    revision_y = m.group(3).decode("ascii", errors="replace")
    return f"R{major}.{revision_x}.{revision_y}"


def _extract_l4t_release_from_path(path: str) -> str | None:
    """Infer the L4T release from the blob's extraction-tree path.

    Complementary fallback to ``_extract_l4t_release`` — kicks in when
    the blob's head bytes don't carry the banner inline (typical for
    standalone bootloader / DTB / MCU blobs) but the blob lives under
    an L4T BSP extraction directory like ``L4T_BSP_SecureBoot.R32.3.1.tar.
    gz_extracted/``.

    Returns ``"R<N>.<x>.<y>"`` (concatenated form, e.g. ``"R32.3.1"``)
    when the path encodes a full triple. Returns ``"R<N>.<x>"`` when
    only major.minor is present (e.g. ``"R28.2"`` for JetPack 3.2). The
    output format matches the 6 forward-prepared pin version_regex
    patterns regardless of which form lands.

    Activation pre-req for the 6 forward-prepared NVIDIA Tegra CVE
    pins on DEVICE_A-class corpus (operator-rebagged BSP archives where
    the L4T release is encoded in the archive filename).
    """
    if not path:
        return None
    m = _L4T_RELEASE_PATH_RE.search(path)
    if not m:
        return None
    # Two alternation arms — group 1+2+3 for triple, group 4+5 for pair.
    if m.group(1) is not None:
        major = m.group(1)
        revision_x = m.group(2)
        revision_y = m.group(3)
        return f"R{major}.{revision_x}.{revision_y}"
    major = m.group(4)
    revision_x = m.group(5)
    return f"R{major}.{revision_x}"


def _read_head(path: str, limit: int) -> bytes:
    """Read up to ``limit`` bytes from ``path``. Empty bytes on any OSError.

    Mirrors ``bt_firmware_banner._read_head`` for consistency.
    """
    try:
        with open(path, "rb") as f:
            return f.read(limit)
    except OSError:
        return b""


def _detect_soc_from_tokens(data: bytes) -> str | None:
    """Return ``t186`` / ``t194`` / ``t210`` / ``t234`` or None.

    Scans ``data`` for SOC tokens in priority order: rodata strings
    (most authoritative), then symbol prefixes. The first hit wins.
    """
    for token, soc in _SOC_TO_CHIPSET.items():
        if token in data:
            return soc
    return None


def _parse_tegra_elf(path: str, head: bytes) -> ParsedBlob | None:
    """ELF disambiguation via byte-scan for Tegra section names /
    symbol prefixes / .rodata SOC strings.

    Returns None if no Tegra evidence is found in the head window
    (caller's filename-stage decision stays authoritative).
    """
    evidence_tokens: list[dict[str, str]] = []

    for section_token in _TEGRA_ELF_SECTION_TOKENS:
        if section_token in head:
            evidence_tokens.append({
                "kind": "section_name",
                "token": section_token.decode("ascii", errors="replace"),
            })

    for symbol_prefix in _TEGRA_ELF_SYMBOL_PREFIXES:
        if symbol_prefix in head:
            evidence_tokens.append({
                "kind": "symbol_prefix",
                "token": symbol_prefix.decode("ascii", errors="replace"),
            })

    soc_token_match: bytes | None = None
    for soc_token in _TEGRA_SOC_TOKENS:
        if soc_token in head:
            evidence_tokens.append({
                "kind": "rodata_soc",
                "token": soc_token.decode("ascii", errors="replace"),
            })
            if soc_token_match is None:
                soc_token_match = soc_token

    if not evidence_tokens:
        return None

    chipset = _detect_soc_from_tokens(head)

    # Confidence: HIGH on section names OR symbol prefixes (these are
    # Tegra-canonical and cannot occur in generic ARM ELFs);
    # MEDIUM when only rodata SOC strings matched (operator may have
    # stripped section names but the build banner survived).
    has_canonical = any(
        t["kind"] in ("section_name", "symbol_prefix")
        for t in evidence_tokens
    )
    confidence = "high" if has_canonical else "medium"

    metadata: dict[str, Any] = {
        "tegra_blob": {
            "subset": "elf",
            "soc_token": chipset,
            "evidence_tokens": evidence_tokens[:8],
            "confidence": confidence,
        },
    }
    # L4T release: TOP-LEVEL string per Reviewer B B4 (2026-05-15)
    # so cve_matcher's one-level-deep _stringify_metadata walker
    # reaches it. Activates the 6 forward-prepared Tegra CVE pins
    # in known_firmware.yaml when the version_regex matches.
    # Two-stage: content-banner first, then path-inference fallback
    # (typical for operator-renamed bootloader blobs landed under an
    # L4T BSP archive directory).
    l4t_release = _extract_l4t_release(head) or _extract_l4t_release_from_path(path)
    if l4t_release is not None:
        metadata["l4t_release"] = l4t_release

    return ParsedBlob(
        vendor="nvidia",
        chipset_target=chipset,
        metadata=metadata,
    )


def _parse_tegra_fdt(path: str, head: bytes) -> ParsedBlob | None:
    """FDT disambiguation via byte-scan for Tegra model/compatible
    strings.

    Returns None for non-Tegra DTBs (caller's filename-stage decision
    stays authoritative; ``parsers/dtb.py`` handles generic DTBs).
    """
    matched_tokens: list[str] = []
    for fdt_token in _TEGRA_FDT_MODEL_TOKENS:
        if fdt_token in head:
            matched_tokens.append(
                fdt_token.decode("ascii", errors="replace")
            )

    if not matched_tokens:
        return None

    chipset = _detect_soc_from_tokens(head)

    metadata: dict[str, Any] = {
        "tegra_blob": {
            "subset": "fdt",
            "soc_token": chipset,
            "evidence_tokens": matched_tokens[:8],
            "confidence": "high",
        },
    }
    # L4T release: TOP-LEVEL string per Reviewer B B4 (2026-05-15).
    # FDT property strings (chosen.bootargs / chosen/nvidia,bootloader)
    # often carry the L4T BSP banner in u-boot-flashed Jetson images.
    # Two-stage: content-banner first, then path-inference fallback.
    l4t_release = _extract_l4t_release(head) or _extract_l4t_release_from_path(path)
    if l4t_release is not None:
        metadata["l4t_release"] = l4t_release

    return ParsedBlob(
        vendor="nvidia",
        chipset_target=chipset,
        metadata=metadata,
    )


def _parse_tegra_android_bootimg(
    path: str, head: bytes,
) -> ParsedBlob | None:
    """Android boot.img — MEDIUM confidence when Tegra hints fire.

    Returns None when no Tegra-specific token is found in the head
    window: generic Android boot.img magic alone is NOT sufficient
    to fabricate Tegra attribution.
    """
    hint_tokens: list[str] = []
    head_lower = head.lower()
    for hint in _TEGRA_BOOTIMG_TOKENS:
        if hint in head_lower:
            hint_tokens.append(
                hint.decode("ascii", errors="replace")
            )

    if not hint_tokens:
        return None

    chipset = _detect_soc_from_tokens(head)

    metadata: dict[str, Any] = {
        "tegra_blob": {
            "subset": "android_bootimg",
            "soc_token": chipset,
            "evidence_tokens": hint_tokens[:8],
            "confidence": "medium",
        },
    }
    # L4T release: TOP-LEVEL string per Reviewer B B4 (2026-05-15).
    # Jetson Linux boot.img cmdline often embeds the BSP release tag.
    # Two-stage: content-banner first, then path-inference fallback.
    l4t_release = _extract_l4t_release(head) or _extract_l4t_release_from_path(path)
    if l4t_release is not None:
        metadata["l4t_release"] = l4t_release

    return ParsedBlob(
        vendor="nvidia",
        chipset_target=chipset,
        metadata=metadata,
    )


def _parse_tegra_deb(path: str) -> ParsedBlob | None:
    """Debian .deb (ar archive) — vendor=debian / package-bundle.

    Tegra-specific refinement happens at the inner-archive layer
    after unblob unpacks the control archive; this parser just
    confirms the outer ar magic and surfaces the container kind.
    """
    return ParsedBlob(
        vendor="debian",
        metadata={
            "tegra_blob": {
                "subset": "deb_ar",
                "soc_token": None,
                "evidence_tokens": ["!<arch>\\n"],
                "confidence": "medium",
                "note": (
                    "Debian ar archive; let unblob unpack the "
                    "control archive for inner-component classification"
                ),
            },
        },
    )


def parse_tegra_blob(
    path: str, magic: bytes, size: int,
) -> ParsedBlob | None:
    """Content-evidence parser for NVIDIA Tegra firmware blobs.

    Dispatches on magic bytes to format-specific subset parsers.
    Returns ``None`` when no Tegra-specific evidence is present
    (caller's filename-stage decision stays authoritative). Sets
    ``vendor="nvidia"`` on every affirmative return EXCEPT for
    Debian ar (where ``vendor="debian"`` — the outer container is
    canonically Debian).

    Args:
        path: Absolute path to the candidate blob.
        magic: First 64 bytes (typically what the detector already read).
        size: Total file size in bytes.

    Returns:
        ParsedBlob with Tegra evidence in ``metadata["tegra_blob"]``,
        or None when no evidence found.

    Per the parser contract: this function MUST NOT raise. On any
    internal error returns None so detection continues for other
    blobs (Rule #34 — graceful degrade).
    """
    if not magic or len(magic) < 4:
        return None

    try:
        # ELF: read up to 64 KB for section / symbol / rodata scan.
        if magic[:4] == _ELF_MAGIC:
            head = _read_head(path, _HEAD_SCAN_BYTES)
            if not head:
                return None
            return _parse_tegra_elf(path, head)

        # FDT (libfdt FDT_MAGIC big-endian).
        if magic[:4] == _FDT_MAGIC:
            head = _read_head(path, _HEAD_SCAN_BYTES)
            if not head:
                return None
            return _parse_tegra_fdt(path, head)

        # Android boot.img.
        if len(magic) >= 8 and magic[:8] == _ANDROID_BOOT_MAGIC:
            head = _read_head(path, _BOOTIMG_CMDLINE_SCAN_BYTES)
            if not head:
                return None
            return _parse_tegra_android_bootimg(path, head)

        # Debian ar (.deb).
        if len(magic) >= 8 and magic[:8] == _DEB_AR_MAGIC:
            return _parse_tegra_deb(path)

        # No Tegra-eligible magic. NVIDIA wrapper (mb1/tos) and BUP
        # container magics are TBD — caller's filename-stage decision
        # carries for those subsets until magic is pinned.
        return None

    except Exception as exc:  # noqa: BLE001 — parser contract: don't raise
        logger.debug(
            "parse_tegra_blob failed on %s: %s", path, exc,
        )
        return None


def merge_tegra_evidence(
    parsed: ParsedBlob, tegra_evidence: ParsedBlob,
) -> ParsedBlob:
    """Merge Tegra second-pass evidence into an existing ParsedBlob.

    Vendor precedence: Tegra evidence wins (per Rule #19 — content
    beats filename) UNLESS the filename-stage parser already set a
    NON-Tegra vendor (e.g. ``vendor="qualcomm"`` from a Qualcomm
    filename pattern — in that case the filename-stage parser knows
    something the byte-scan doesn't, so we don't override).

    chipset_target: Tegra value populates only when ``parsed.chipset_
    target`` is None (the filename-stage parser may already have a
    more specific value).

    metadata: Tegra metadata merges under the existing dict; the
    ``tegra_blob`` key is overwritten (Tegra evidence is the
    authoritative source for that sub-tree).
    """
    if tegra_evidence.vendor == "nvidia":
        # Tegra evidence overrides None / "unknown" / non-nvidia
        # vendors EXCEPT when the filename-stage parser confidently
        # set a competing vendor (qualcomm / mediatek / etc.). The
        # competing-vendor case is rare for Tegra magic (ELF/FDT/
        # Android-boot/ar) but worth guarding against false-positives.
        if parsed.vendor in (None, "unknown", "nvidia"):
            parsed.vendor = "nvidia"
    elif tegra_evidence.vendor == "debian":
        # Debian .deb — only override if the filename-stage parser
        # didn't already set a more specific vendor.
        if parsed.vendor in (None, "unknown"):
            parsed.vendor = "debian"

    if tegra_evidence.chipset_target and not parsed.chipset_target:
        parsed.chipset_target = tegra_evidence.chipset_target

    if tegra_evidence.metadata:
        if parsed.metadata is None:
            parsed.metadata = {}
        for key, value in tegra_evidence.metadata.items():
            parsed.metadata[key] = value

    return parsed


__all__ = [
    "parse_tegra_blob",
    "merge_tegra_evidence",
]
