"""Durable backstop: ``alembic check`` must report no drift.

The audit-2026-05-05 (`audit-models-orm-vs-db-schema-drift-2026-05-05.md`)
and audit-2026-05-07 (`audit-db-alembic-chain-drift-2026-05-07.md`) both
left this gate as a follow-up. Two orthogonal drift classes are caught
in one shot:

1. **ORM-vs-DB drift** (Family A / Family B from the 2026-05-05 audit) —
   a model edit that adds/removes/changes a column, index, or constraint
   without an accompanying alembic migration. ``alembic check`` runs
   autogenerate-compare and emits the exact ``op.*`` calls that would be
   needed to bring the DB into alignment.

2. **DB-vs-chain drift** (F-C-05 from the 2026-05-07 audit) — DDL state
   remains applied in the DB after a migration file is deleted from
   ``backend/alembic/versions/``. The same compare detects the inverse:
   the DB has DDL the model doesn't expect, so autogenerate proposes to
   drop it.

Either failure mode raises ``AutogenerateDiffsDetected``. The test
re-formats the exception so the failure message points at the playbook
and the specific drift.

Runs against the live ``wairz`` DB at HEAD inside the backend container
(the same DB used by the rest of the test suite). No state is mutated;
``alembic check`` is read-only.
"""
from __future__ import annotations

from pathlib import Path

import pytest
from alembic.config import Config
from alembic.util import exc as alembic_exc

from alembic import command

_BACKEND_DIR = Path(__file__).parent.parent
_ALEMBIC_INI = _BACKEND_DIR / "alembic.ini"


def test_alembic_autogenerate_is_empty() -> None:
    """``alembic check`` must produce no pending upgrade ops.

    Failure means either the ORM models added/removed/changed
    columns/indexes/constraints WITHOUT a migration (Family A/B drift),
    OR a migration was deleted while its DDL remains in the DB (F-C-05
    drift). The exception's repr lists the exact drift; the playbook
    for resolution lives in
    ``.planning/intake/resolved/audit-models-orm-vs-db-schema-drift-2026-05-05.md``.
    """
    assert _ALEMBIC_INI.exists(), (
        f"alembic.ini not found at {_ALEMBIC_INI} — "
        "test must run inside the backend container with the backend "
        "tree mounted at /app or with the standard wairz repo layout."
    )
    cfg = Config(str(_ALEMBIC_INI))
    try:
        command.check(cfg)
    except alembic_exc.AutogenerateDiffsDetected as drift:
        pytest.fail(
            "alembic autogenerate detected drift between ORM models "
            "and the live wairz database — either ship a migration or "
            "update the model __table_args__ to match the DB.\n"
            f"  Drift: {drift}\n"
            "Playbook: "
            ".planning/intake/resolved/audit-models-orm-vs-db-schema-drift-2026-05-05.md"
        )
