from datetime import datetime, timezone
from html import escape

from app.models.finding import Finding
from app.models.firmware import Firmware
from app.models.project import Project

SEVERITY_ORDER = {"critical": 0, "high": 1, "medium": 2, "low": 3, "info": 4}
SEVERITY_EMOJI = {"critical": "!!!", "high": "!!", "medium": "!", "low": "-", "info": "i"}
SEVERITY_COLORS = {
    "critical": ("#991b1b", "#fef2f2", "#fecaca"),
    "high": ("#9a3412", "#fff7ed", "#fed7aa"),
    "medium": ("#854d0e", "#fefce8", "#fef08a"),
    "low": ("#1e40af", "#eff6ff", "#bfdbfe"),
    "info": ("#374151", "#f9fafb", "#e5e7eb"),
}


def generate_markdown_report(
    project: Project,
    firmware: Firmware | None,
    findings: list[Finding],
) -> str:
    """Generate a Markdown security assessment report."""
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    sections: list[str] = []

    # Title
    sections.append(f"# Security Assessment Report: {project.name}\n")
    sections.append(f"**Generated:** {now}  ")
    sections.append(f"**Project:** {project.name}  ")
    if project.description:
        sections.append(f"**Description:** {project.description}  ")
    sections.append("")

    # Firmware info
    if firmware:
        sections.append("## Firmware Information\n")
        sections.append(f"| Property | Value |")
        sections.append(f"|---|---|")
        if firmware.original_filename:
            sections.append(f"| Filename | {firmware.original_filename} |")
        sections.append(f"| SHA256 | `{firmware.sha256}` |")
        if firmware.file_size:
            size_mb = firmware.file_size / (1024 * 1024)
            sections.append(f"| File Size | {size_mb:.1f} MB ({firmware.file_size:,} bytes) |")
        if firmware.architecture:
            sections.append(f"| Architecture | {firmware.architecture} |")
        if firmware.endianness:
            sections.append(f"| Endianness | {firmware.endianness} |")
        if firmware.os_info:
            sections.append(f"| OS Info | {firmware.os_info} |")
        sections.append("")

    # Executive summary
    sections.append("## Executive Summary\n")
    if not findings:
        sections.append("No security findings were recorded for this project.\n")
    else:
        by_severity: dict[str, list[Finding]] = {}
        for f in findings:
            by_severity.setdefault(f.severity, []).append(f)

        total = len(findings)
        summary_parts = []
        for sev in ["critical", "high", "medium", "low", "info"]:
            count = len(by_severity.get(sev, []))
            if count:
                summary_parts.append(f"**{count}** {sev}")

        sections.append(
            f"A total of **{total}** finding(s) were identified: "
            + ", ".join(summary_parts)
            + ".\n"
        )

        # Summary table
        sections.append("| Severity | Count |")
        sections.append("|---|---|")
        for sev in ["critical", "high", "medium", "low", "info"]:
            count = len(by_severity.get(sev, []))
            if count:
                sections.append(f"| {sev.capitalize()} | {count} |")
        sections.append("")

    # Findings by severity
    if findings:
        sorted_findings = sorted(
            findings, key=lambda f: (SEVERITY_ORDER.get(f.severity, 99), f.title)
        )

        sections.append("## Findings\n")

        current_severity = None
        for f in sorted_findings:
            if f.severity != current_severity:
                current_severity = f.severity
                sections.append(f"### {current_severity.capitalize()} Severity\n")

            sections.append(f"#### {f.title}\n")
            sections.append(f"**Severity:** {f.severity.capitalize()}  ")
            sections.append(f"**Status:** {f.status}  ")
            if f.file_path:
                line_info = f":{f.line_number}" if f.line_number else ""
                sections.append(f"**File:** `{f.file_path}{line_info}`  ")
            if f.cve_ids:
                sections.append(f"**CVEs:** {', '.join(f.cve_ids)}  ")
            if f.cwe_ids:
                sections.append(f"**CWEs:** {', '.join(f.cwe_ids)}  ")
            sections.append("")

            if f.description:
                sections.append(f"{f.description}\n")

            if f.evidence:
                sections.append("**Evidence:**\n")
                sections.append(f"```\n{f.evidence}\n```\n")

    # Footer
    sections.append("---\n")
    sections.append("*Report generated by [Wairz](https://wairz.ai) — AI-Assisted Firmware Security Assessment*\n")

    return "\n".join(sections)


def _severity_badge_html(severity: str) -> str:
    text_color, _, bg_color = SEVERITY_COLORS.get(severity, SEVERITY_COLORS["info"])
    return (
        f'<span style="display:inline-block;padding:2px 10px;border-radius:9999px;'
        f"font-size:12px;font-weight:600;color:{text_color};background:{bg_color};\">"
        f"{escape(severity.capitalize())}</span>"
    )


def generate_html_report(
    project: Project,
    firmware: Firmware | None,
    findings: list[Finding],
) -> str:
    """Generate a self-contained HTML security assessment report."""
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    e = escape  # shorthand

    # Build firmware info rows
    fw_rows = ""
    if firmware:
        if firmware.original_filename:
            fw_rows += f"<tr><td>Filename</td><td>{e(firmware.original_filename)}</td></tr>"
        fw_rows += f"<tr><td>SHA256</td><td><code>{e(firmware.sha256)}</code></td></tr>"
        if firmware.file_size:
            size_mb = firmware.file_size / (1024 * 1024)
            fw_rows += f"<tr><td>File Size</td><td>{size_mb:.1f} MB ({firmware.file_size:,} bytes)</td></tr>"
        if firmware.architecture:
            fw_rows += f"<tr><td>Architecture</td><td>{e(firmware.architecture)}</td></tr>"
        if firmware.endianness:
            fw_rows += f"<tr><td>Endianness</td><td>{e(firmware.endianness)}</td></tr>"
        if firmware.os_info:
            fw_rows += f"<tr><td>OS Info</td><td>{e(firmware.os_info)}</td></tr>"

    # Executive summary
    by_severity: dict[str, list[Finding]] = {}
    for f in findings:
        by_severity.setdefault(f.severity, []).append(f)

    summary_badges = ""
    summary_text = ""
    if findings:
        total = len(findings)
        badge_parts = []
        for sev in ["critical", "high", "medium", "low", "info"]:
            count = len(by_severity.get(sev, []))
            if count:
                badge_parts.append(f"{_severity_badge_html(sev)} {count}")
        summary_badges = "&nbsp;&nbsp;".join(badge_parts)
        summary_text = f"A total of <strong>{total}</strong> finding(s) were identified."
    else:
        summary_text = "No security findings were recorded for this project."

    # Findings sections grouped by severity
    findings_html = ""
    if findings:
        sorted_findings = sorted(
            findings, key=lambda f: (SEVERITY_ORDER.get(f.severity, 99), f.title)
        )
        current_severity = None
        for f in sorted_findings:
            if f.severity != current_severity:
                if current_severity is not None:
                    findings_html += "</div>"  # close previous severity section
                current_severity = f.severity
                text_color, bg_light, _ = SEVERITY_COLORS.get(
                    current_severity, SEVERITY_COLORS["info"]
                )
                findings_html += (
                    f'<div class="severity-section" style="page-break-before:auto;">'
                    f"<h2 style=\"color:{text_color};border-bottom:2px solid {text_color};"
                    f'padding-bottom:4px;">{e(current_severity.capitalize())} Severity</h2>'
                )

            # Finding card
            findings_html += f'<div class="finding-card">'
            findings_html += (
                f'<h3 style="margin:0 0 8px 0;">'
                f"{_severity_badge_html(f.severity)} {e(f.title)}</h3>"
            )
            meta_parts = [f"<strong>Status:</strong> {e(f.status)}"]
            if f.file_path:
                line_info = f":{f.line_number}" if f.line_number else ""
                meta_parts.append(
                    f"<strong>File:</strong> <code>{e(f.file_path)}{line_info}</code>"
                )
            if f.cve_ids:
                meta_parts.append(
                    f"<strong>CVEs:</strong> {e(', '.join(f.cve_ids))}"
                )
            if f.cwe_ids:
                meta_parts.append(
                    f"<strong>CWEs:</strong> {e(', '.join(f.cwe_ids))}"
                )
            findings_html += (
                '<p style="font-size:13px;color:#555;margin:0 0 8px 0;">'
                + " &nbsp;|&nbsp; ".join(meta_parts)
                + "</p>"
            )

            if f.description:
                findings_html += f"<p>{e(f.description)}</p>"
            if f.evidence:
                findings_html += (
                    f"<div><strong>Evidence:</strong></div>"
                    f"<pre><code>{e(f.evidence)}</code></pre>"
                )
            findings_html += "</div>"

        if current_severity is not None:
            findings_html += "</div>"  # close last severity section

    html = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Security Assessment Report: {e(project.name)}</title>
<style>
  @page {{
    size: A4;
    margin: 20mm 15mm;
    @bottom-center {{
      content: "Page " counter(page) " of " counter(pages);
      font-size: 10px;
      color: #999;
    }}
  }}
  body {{
    font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
    color: #1a1a1a;
    line-height: 1.6;
    max-width: 800px;
    margin: 0 auto;
    padding: 0 20px;
    font-size: 14px;
  }}
  h1 {{
    color: #111827;
    border-bottom: 3px solid #2563eb;
    padding-bottom: 8px;
  }}
  h2 {{
    margin-top: 28px;
  }}
  table {{
    width: 100%;
    border-collapse: collapse;
    margin: 12px 0;
  }}
  th, td {{
    border: 1px solid #d1d5db;
    padding: 8px 12px;
    text-align: left;
  }}
  th {{
    background: #f3f4f6;
    font-weight: 600;
  }}
  code {{
    background: #f3f4f6;
    padding: 1px 4px;
    border-radius: 3px;
    font-size: 13px;
  }}
  pre {{
    background: #1e293b;
    color: #e2e8f0;
    padding: 12px 16px;
    border-radius: 6px;
    overflow-x: auto;
    font-size: 12px;
    line-height: 1.5;
  }}
  pre code {{
    background: none;
    padding: 0;
    color: inherit;
  }}
  .finding-card {{
    border: 1px solid #e5e7eb;
    border-radius: 8px;
    padding: 16px;
    margin: 12px 0;
    background: #fafafa;
  }}
  .header-meta {{
    color: #6b7280;
    font-size: 13px;
    margin: 4px 0;
  }}
  .footer {{
    margin-top: 40px;
    padding-top: 16px;
    border-top: 1px solid #d1d5db;
    text-align: center;
    color: #9ca3af;
    font-size: 12px;
  }}
</style>
</head>
<body>

<h1>Security Assessment Report</h1>
<p class="header-meta"><strong>Project:</strong> {e(project.name)}</p>
{"<p class='header-meta'><strong>Description:</strong> " + e(project.description) + "</p>" if project.description else ""}
<p class="header-meta"><strong>Generated:</strong> {now}</p>

{"<h2>Firmware Information</h2><table><tbody>" + fw_rows + "</tbody></table>" if fw_rows else ""}

<h2>Executive Summary</h2>
<p>{summary_text}</p>
{"<p>" + summary_badges + "</p>" if summary_badges else ""}

{findings_html}

<div class="footer">
  Report generated by <strong>Wairz</strong> — AI-Assisted Firmware Security Assessment<br>
  <a href="https://wairz.ai" style="color:#2563eb;">wairz.ai</a>
</div>

</body>
</html>"""
    return html


def generate_pdf_report(
    project: Project,
    firmware: Firmware | None,
    findings: list[Finding],
) -> bytes:
    """Generate a PDF security assessment report via weasyprint."""
    import weasyprint

    html = generate_html_report(project, firmware, findings)
    return weasyprint.HTML(string=html).write_pdf()
