from datetime import datetime, timezone

from app.models.finding import Finding
from app.models.firmware import Firmware
from app.models.project import Project

SEVERITY_ORDER = {"critical": 0, "high": 1, "medium": 2, "low": 3, "info": 4}
SEVERITY_EMOJI = {"critical": "!!!", "high": "!!", "medium": "!", "low": "-", "info": "i"}


def generate_markdown_report(
    project: Project,
    firmware: Firmware | None,
    findings: list[Finding],
) -> str:
    """Generate a Markdown security assessment report."""
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    sections: list[str] = []

    # Title
    sections.append(f"# Security Assessment Report: {project.name}\n")
    sections.append(f"**Generated:** {now}  ")
    sections.append(f"**Project:** {project.name}  ")
    if project.description:
        sections.append(f"**Description:** {project.description}  ")
    sections.append("")

    # Firmware info
    if firmware:
        sections.append("## Firmware Information\n")
        sections.append(f"| Property | Value |")
        sections.append(f"|---|---|")
        if firmware.original_filename:
            sections.append(f"| Filename | {firmware.original_filename} |")
        sections.append(f"| SHA256 | `{firmware.sha256}` |")
        if firmware.file_size:
            size_mb = firmware.file_size / (1024 * 1024)
            sections.append(f"| File Size | {size_mb:.1f} MB ({firmware.file_size:,} bytes) |")
        if firmware.architecture:
            sections.append(f"| Architecture | {firmware.architecture} |")
        if firmware.endianness:
            sections.append(f"| Endianness | {firmware.endianness} |")
        if firmware.os_info:
            sections.append(f"| OS Info | {firmware.os_info} |")
        sections.append("")

    # Executive summary
    sections.append("## Executive Summary\n")
    if not findings:
        sections.append("No security findings were recorded for this project.\n")
    else:
        by_severity: dict[str, list[Finding]] = {}
        for f in findings:
            by_severity.setdefault(f.severity, []).append(f)

        total = len(findings)
        summary_parts = []
        for sev in ["critical", "high", "medium", "low", "info"]:
            count = len(by_severity.get(sev, []))
            if count:
                summary_parts.append(f"**{count}** {sev}")

        sections.append(
            f"A total of **{total}** finding(s) were identified: "
            + ", ".join(summary_parts)
            + ".\n"
        )

        # Summary table
        sections.append("| Severity | Count |")
        sections.append("|---|---|")
        for sev in ["critical", "high", "medium", "low", "info"]:
            count = len(by_severity.get(sev, []))
            if count:
                sections.append(f"| {sev.capitalize()} | {count} |")
        sections.append("")

    # Findings by severity
    if findings:
        sorted_findings = sorted(
            findings, key=lambda f: (SEVERITY_ORDER.get(f.severity, 99), f.title)
        )

        sections.append("## Findings\n")

        current_severity = None
        for f in sorted_findings:
            if f.severity != current_severity:
                current_severity = f.severity
                sections.append(f"### {current_severity.capitalize()} Severity\n")

            sections.append(f"#### {f.title}\n")
            sections.append(f"**Severity:** {f.severity.capitalize()}  ")
            sections.append(f"**Status:** {f.status}  ")
            if f.file_path:
                line_info = f":{f.line_number}" if f.line_number else ""
                sections.append(f"**File:** `{f.file_path}{line_info}`  ")
            if f.cve_ids:
                sections.append(f"**CVEs:** {', '.join(f.cve_ids)}  ")
            sections.append("")

            if f.description:
                sections.append(f"{f.description}\n")

            if f.evidence:
                sections.append("**Evidence:**\n")
                sections.append(f"```\n{f.evidence}\n```\n")

    # Footer
    sections.append("---\n")
    sections.append("*Report generated by [Wairz](https://wairz.ai) — AI-Assisted Firmware Security Assessment*\n")

    return "\n".join(sections)
