"""add_analysis_cache_table

Revision ID: 01ac34151ca4
Revises: 66238ac7e12c
Create Date: 2026-02-14 09:54:05.600162

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '01ac34151ca4'
down_revision: Union[str, None] = '66238ac7e12c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analysis_cache',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('firmware_id', sa.Uuid(), nullable=False),
    sa.Column('binary_path', sa.String(length=512), nullable=True),
    sa.Column('binary_sha256', sa.String(length=64), nullable=True),
    sa.Column('operation', sa.String(length=100), nullable=False),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['firmware_id'], ['firmware.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_cache_lookup', 'analysis_cache', ['firmware_id', 'binary_sha256', 'operation'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_cache_lookup', table_name='analysis_cache')
    op.drop_table('analysis_cache')
    # ### end Alembic commands ###
