"""initial schema

Revision ID: 1ad845518fb9
Revises: 
Create Date: 2026-02-12 17:29:16.781604

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ad845518fb9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), server_default='created', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('firmware',
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=True),
    sa.Column('storage_path', sa.String(length=512), nullable=True),
    sa.Column('extracted_path', sa.String(length=512), nullable=True),
    sa.Column('architecture', sa.String(length=50), nullable=True),
    sa.Column('endianness', sa.String(length=10), nullable=True),
    sa.Column('os_info', sa.Text(), nullable=True),
    sa.Column('unpack_log', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('firmware')
    op.drop_table('projects')
    # ### end Alembic commands ###
