"""add cwe_ids to findings

Revision ID: 6544325a309a
Revises: 91333b7f0e16
Create Date: 2026-02-14 14:18:40.569221

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6544325a309a'
down_revision: Union[str, None] = '91333b7f0e16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('findings', sa.Column('cwe_ids', sa.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('findings', 'cwe_ids')
    # ### end Alembic commands ###
