/** Short descriptions for common CWEs encountered in firmware security analysis. */
const CWE_DESCRIPTIONS: Record<string, string> = {
  'CWE-20': 'Improper Input Validation',
  'CWE-22': 'Improper Limitation of a Pathname to a Restricted Directory (Path Traversal)',
  'CWE-23': 'Relative Path Traversal',
  'CWE-36': 'Absolute Path Traversal',
  'CWE-59': 'Improper Link Resolution Before File Access (Link Following)',
  'CWE-73': 'External Control of File Name or Path',
  'CWE-77': 'Improper Neutralization of Special Elements used in a Command (Command Injection)',
  'CWE-78': 'Improper Neutralization of Special Elements used in an OS Command (OS Command Injection)',
  'CWE-79': 'Improper Neutralization of Input During Web Page Generation (XSS)',
  'CWE-89': 'Improper Neutralization of Special Elements used in an SQL Command (SQL Injection)',
  'CWE-94': 'Improper Control of Generation of Code (Code Injection)',
  'CWE-119': 'Improper Restriction of Operations within the Bounds of a Memory Buffer',
  'CWE-120': 'Buffer Copy without Checking Size of Input (Classic Buffer Overflow)',
  'CWE-121': 'Stack-based Buffer Overflow',
  'CWE-122': 'Heap-based Buffer Overflow',
  'CWE-125': 'Out-of-bounds Read',
  'CWE-126': 'Buffer Over-read',
  'CWE-131': 'Incorrect Calculation of Buffer Size',
  'CWE-134': 'Use of Externally-Controlled Format String',
  'CWE-170': 'Improper Null Termination',
  'CWE-190': 'Integer Overflow or Wraparound',
  'CWE-200': 'Exposure of Sensitive Information to an Unauthorized Actor',
  'CWE-209': 'Generation of Error Message Containing Sensitive Information',
  'CWE-215': 'Insertion of Sensitive Information Into Debugging Code',
  'CWE-250': 'Execution with Unnecessary Privileges',
  'CWE-252': 'Unchecked Return Value',
  'CWE-256': 'Plaintext Storage of a Password',
  'CWE-259': 'Use of Hard-coded Password',
  'CWE-269': 'Improper Privilege Management',
  'CWE-276': 'Incorrect Default Permissions',
  'CWE-284': 'Improper Access Control',
  'CWE-287': 'Improper Authentication',
  'CWE-295': 'Improper Certificate Validation',
  'CWE-306': 'Missing Authentication for Critical Function',
  'CWE-307': 'Improper Restriction of Excessive Authentication Attempts',
  'CWE-311': 'Missing Encryption of Sensitive Data',
  'CWE-312': 'Cleartext Storage of Sensitive Information',
  'CWE-319': 'Cleartext Transmission of Sensitive Information',
  'CWE-320': 'Key Management Errors',
  'CWE-321': 'Use of Hard-coded Cryptographic Key',
  'CWE-326': 'Inadequate Encryption Strength',
  'CWE-327': 'Use of a Broken or Risky Cryptographic Algorithm',
  'CWE-328': 'Use of Weak Hash',
  'CWE-330': 'Use of Insufficiently Random Values',
  'CWE-338': 'Use of Cryptographically Weak Pseudo-Random Number Generator (PRNG)',
  'CWE-345': 'Insufficient Verification of Data Authenticity',
  'CWE-346': 'Origin Validation Error',
  'CWE-352': 'Cross-Site Request Forgery (CSRF)',
  'CWE-362': 'Concurrent Execution using Shared Resource with Improper Synchronization (Race Condition)',
  'CWE-377': 'Insecure Temporary File',
  'CWE-400': 'Uncontrolled Resource Consumption',
  'CWE-415': 'Double Free',
  'CWE-416': 'Use After Free',
  'CWE-426': 'Untrusted Search Path',
  'CWE-427': 'Uncontrolled Search Path Element',
  'CWE-434': 'Unrestricted Upload of File with Dangerous Type',
  'CWE-476': 'NULL Pointer Dereference',
  'CWE-494': 'Download of Code Without Integrity Check',
  'CWE-502': 'Deserialization of Untrusted Data',
  'CWE-522': 'Insufficiently Protected Credentials',
  'CWE-532': 'Insertion of Sensitive Information into Log File',
  'CWE-541': 'Inclusion of Sensitive Information in an Include File',
  'CWE-546': 'Suspicious Comment',
  'CWE-547': 'Use of Hard-coded, Security-relevant Constants',
  'CWE-552': 'Files or Directories Accessible to External Parties',
  'CWE-561': 'Dead Code',
  'CWE-601': 'URL Redirection to Untrusted Site (Open Redirect)',
  'CWE-611': 'Improper Restriction of XML External Entity Reference',
  'CWE-614': 'Sensitive Cookie in HTTPS Session Without "Secure" Attribute',
  'CWE-615': 'Inclusion of Sensitive Information in Source Code Comments',
  'CWE-620': 'Unverified Password Change',
  'CWE-640': 'Weak Password Recovery Mechanism for Forgotten Password',
  'CWE-662': 'Improper Synchronization',
  'CWE-668': 'Exposure of Resource to Wrong Sphere',
  'CWE-676': 'Use of Potentially Dangerous Function',
  'CWE-693': 'Protection Mechanism Failure',
  'CWE-732': 'Incorrect Permission Assignment for Critical Resource',
  'CWE-757': 'Selection of Less-Secure Algorithm During Negotiation (Algorithm Downgrade)',
  'CWE-759': 'Use of a One-Way Hash without a Salt',
  'CWE-760': 'Use of a One-Way Hash with a Predictable Salt',
  'CWE-770': 'Allocation of Resources Without Limits or Throttling',
  'CWE-772': 'Missing Release of Resource after Effective Lifetime',
  'CWE-787': 'Out-of-bounds Write',
  'CWE-798': 'Use of Hard-coded Credentials',
  'CWE-807': 'Reliance on Untrusted Inputs in a Security Decision',
  'CWE-829': 'Inclusion of Functionality from Untrusted Control Sphere',
  'CWE-862': 'Missing Authorization',
  'CWE-863': 'Incorrect Authorization',
  'CWE-916': 'Use of Password Hash With Insufficient Computational Effort',
  'CWE-918': 'Server-Side Request Forgery (SSRF)',
  'CWE-922': 'Insecure Storage of Sensitive Information',
  'CWE-1188': 'Initialization with Hard-Coded Network Resource Configuration Data',
  'CWE-1236': 'Improper Neutralization of Formula Elements in a CSV File',
  'CWE-1321': 'Improperly Controlled Modification of Object Prototype Attributes (Prototype Pollution)',
  'CWE-1392': 'Use of Default Credentials',
}

/**
 * Get a short description for a CWE ID.
 * Returns undefined if the CWE is not in the local database.
 */
export function getCweDescription(cweId: string): string | undefined {
  return CWE_DESCRIPTIONS[cweId.toUpperCase()]
}

/**
 * Build the MITRE CWE page URL from a CWE ID string like "CWE-798".
 */
export function getCweMitreUrl(cweId: string): string {
  const num = cweId.replace(/^CWE-/i, '')
  return `https://cwe.mitre.org/data/definitions/${num}.html`
}
